routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

// Route::resource('companies', 'App\Http\Controllers\CompanyController');

Route::resource('companies', 'App\Http\Controllers\CompanyController')->except([
    'create', 'show'
]);

Route::delete('deleteCompany', 'App\Http\Controllers\CompanyController@destroy')->name('remove');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    use HasFactory;


    protected $guarded = [];
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Company;

use Illuminate\Support\Facades\Storage;
use DataTables;

class CompanyController extends Controller
{


    public function __construct()
    {
        $this->middleware('auth');
    }


    public function index(Request $request)
    {
        if ($request->ajax()) {
            $companies = Company::all();
            return DataTables::of($companies)
                ->addColumn('action', function ($company) {
                    $editUrl = route('companies.edit', $company->id);
                    $deleteUrl = route('companies.destroy', $company->id);
                    $csrfToken = csrf_token();

                    $btn = '<a href="javascript:void(0)" data-toggle="tooltip"  data-id="'.$company->id.'" data-original-title="Edit" class="edit btn btn-primary btn-sm editPost">Edit</a>';

                    $btn = $btn.' <a href="javascript:void(0)" data-toggle="tooltip"  data-id="'.$company->id.'" data-original-title="Delete" class="btn btn-danger btn-sm deletePost">Delete</a>';
                    return $btn;
                    //  "<a href='#' data-toggle='modal' data-target='#addCompanyModal'
                    // data-id=$company->id


                    // class='btn btn-sm btn-primary'>Edit</a>
                    //         <button type='button' class='btn btn-sm btn-danger' onclick='deleteCompany({$company->id}, \"{$deleteUrl}\", \"{$csrfToken}\")'>Delete</button>";
                })
                ->rawColumns(['action'])
                ->make(true);
        }

        return view('companies.index');
    }

    public function store(Request $request)
    {    logger($request->all());

        $validatedData = $request->validate([
            'name' => 'required',
            'email' => 'nullable|email',
            'logo' => 'nullable|image|mimes:jpeg,png,jpg,gif,svg|max:204888',
            'website' => 'nullable',
        ]);


        if ($request->hasFile('logo')) {
            $logo = $request->file('logo');
            $logoPath = $logo->store('public/logos');
            $validatedData['logo'] = str_replace("public/logos/", "", $logoPath);
        }
logger($validatedData);

        $company = Company::updateOrCreate( ['id' => $request->company_id] , $validatedData);

        return response()->json(['success' => true, 'message' => 'success.', 'company' => $company]);
    }

    public function update(Request $request, $id)
    {
        $validatedData = $request->validate([
            'name' => 'required',
            'email' => 'nullable|email',
            'logo' => 'nullable|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'website' => 'nullable',
        ]);

        $company = Company::findOrFail($id);

        if ($request->hasFile('logo')) {
            $logo = $request->file('logo');
            $logoPath = $logo->store('public/logos');
            $validatedData['logo'] = $logoPath;
        }

        $company->update($validatedData);

        return response()->json(['success' => true, 'message' => 'Company updated successfully.']);
    }



    public function edit($id)
    {
        $post = Company::findOrFail($id);
        return response()->json($post);
    }

    public function destroy($id)
    {   logger($id);
        $company = Company::findOrFail($id);
        $company->delete();

        return response()->json(['success' => true, 'message' => 'Company deleted successfully.']);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('companies.index');
    }
}

resources/views/companies/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row mb-3">
            <div class="col-md-12">
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addCompanyModal">
                    Add Company
                </button>
            </div>
        </div>
        <table id="companyTable" class="display">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Logo</th>
                    <th>Website</th>
                    <th>Action</th>
                </tr>
            </thead>
        </table>
    </div>

    <!-- Add Company Modal -->
    <div class="modal fade" id="addCompanyModal" tabindex="-1" role="dialog" aria-labelledby="addCompanyModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="addCompanyModalLabel">Add Company</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form id="addCompanyForm" action="{{route('companies.store')}}">
                        @csrf <!-- {{ csrf_field() }} -->
                        <div class="form-group">
                            <label for="name">Name</label>
                            <input type="text" class="form-control" id="name" name="name" required>
                        </div>
                        <div class="form-group">
                            <label for="email">Email</label>
                            <input type="email" class="form-control" id="email" name="email">
                        </div>
                        <div class="form-group">
                            <label for="logo">Logo</label>
                            <input type="file" accept="image/png, image/gif, image/jpeg"  class="form-control-file" id="logo" name="logo">
                        </div>
                        <div class="form-group">
                            <label for="website">Website</label>
                            <input type="text" class="form-control" id="website" name="website">
                        </div>
                        <button type="submit" class="btn btn-primary">Add</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Edit Company Modal -->
    <div class="modal fade" id="editCompanyModal" tabindex="-1" role="dialog" aria-labelledby="editCompanyModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="editCompanyModalLabel">Edit Company</h5>
                    <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form id="editCompanyForm" action="{{route('companies.store')}}">
                        @csrf <!-- {{ csrf_field() }} -->
                        <input type="hidden" name="company_id" id="company_id">
                        <div class="form-group">
                            <label for="edit_name">Name</label>
                            <input type="text" class="form-control" id="edit_name" name="name" required>
                        </div>
                        <div class="form-group">
                            <label for="edit_email">Email</label>
                            <input type="email" class="form-control" id="edit_email" name="email">
                        </div>

                        <div class="form-group">
                            <img id="logo_view" src="" width="100" height="100" alt="Insert link 1 alt text here" />
                            <label for="edit_logo"> Logo</label>
                            <input type="file" accept="image/png, image/gif, image/jpeg"  class="form-control-file" id="edit_logo" name="logo">
                        </div>
                        <div class="form-group">
                            <label for="edit_website">Website</label>
                            <input type="text" class="form-control" id="edit_website" name="website">
                        </div>
                        <button type="submit" class="btn btn-primary">Update</button>
                    </form>
                </div>
            </div>
        </div>
    </div>



    <script>
        $(document).ready(function() {
            // Initialize DataTable with search and pagination
            var companyTable = $('#companyTable').DataTable({
                processing: true,
                serverSide: true,
                ajax: '{{ route('companies.index') }}',
                columns: [
                    { data: 'name', name: 'name' },
                    { data: 'email', name: 'email' },
                    {
                        data: 'logo',
                        name: 'logo',
                        render: function(data, type, full, meta) {
                            if (data) {
                                    //  alert("{{  url('/storage/logos')}}" + '/' + data)
                                return '<img src="{{  url('/storage/logos')}}/' + data + '"  width="100" height="100" alt="Company Logo" >';
                            } else {
                                return '';
                            }
                        }
                    },
                    { data: 'website', name: 'website' },
                    { data: 'action', name: 'action', orderable: false, searchable: false }
                ],
                "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
                "pageLength": 10
            });

            // Add Company form submission using AJAX
            $('#addCompanyForm').submit(function(e) {
                e.preventDefault();

                var form = $(this);
                var url = form.attr('action');
                var formData = new FormData(form[0]);

                var resource = $(this).data("resource");



                $.ajax({
                    url: url,
                    type: 'POST',
                    data: formData,
                    processData: false,
                    contentType: false,
                    success: function(response) {
                        if (response.success) {
                            alert(response.message);
                            companyTable.ajax.reload();
                            $('#addCompanyModal').modal('hide');


                            form.trigger('reset');
                        } else {
                            alert('Error adding company. Please check input.');
                        }
                    },
                    error: function(xhr, textStatus, errorThrown) {
                        alert('Error adding company. Please try again.');
                    }
                });
            });

            // Edit Company form submission using AJAX
            $('#editCompanyForm').submit(function(e) {
                e.preventDefault();

                var form = $(this);
                var url = form.attr('action');
                var formData = new FormData(form[0]);

                $.ajax({
                    url: url,
                    type: 'POST',
                    data: formData,
                    processData: false,
                    contentType: false,
                    success: function(response) {
                        if (response.success) {
                            alert(response.message);
                            companyTable.ajax.reload();
                            $('#editCompanyModal').modal('hide');
                            form.trigger('reset');
                        } else {
                            alert('Error updating company. Please try again.');
                        }
                    },
                    error: function(xhr, textStatus, errorThrown) {
                        alert('Error updating company. Please try again.');
                    }
                });
            });




            $('body').on('click', '.editPost', function () {

      var id = $(this).data('id');
      $.get("{{ route('companies.index') }}" +'/' + id +'/edit', function (data) {
        //alert("{{  url('/storage/logos')}}" + '/' + data.logo)
        $("#logo_view").attr("src","{{  url('/storage/logos')}}" + '/' + data.logo);
        $('#edit_website').val(data.website);
          $('#modelHeading').html("Edit Post");
          $('#savedata').val("edit-user");
          $('#editCompanyModal').modal('show');
          $('#company_id').val(data.id);
          $('#edit_name').val(data.name);
          $('#edit_email').val(data.email);
          $('#edit_logo').val(data.logo);




      })
   });





   $('body').on('click', '.deletePost', function () {

     var id = $(this).data("id");
     var url = "{{ route('companies.destroy', ":id") }}";
     url = url.replace(':id', id);

     confirm("Are You sure want to delete !");

     $.ajaxSetup({
    headers: {
        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
    }
});

     $.ajax({
         type: 'delete',
         data: { "id": id},
         datatype : 'json',
         url: url,
         success: function (data) {
            $('#companyTable').DataTable().ajax.reload();
         },
         error: function (data) {
             alert('Error:', data);
         }
     });
 });



        });
    </script>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">


    <title>{{ config('app.name', 'Laravel') }}</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/4.6.0/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css">

    <script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/4.6.0/js/bootstrap.bundle.min.js"></script>




    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=Nunito" rel="stylesheet">

    <!-- Scripts -->
    @vite(['resources/sass/app.scss', 'resources/js/app.js'])
</head>



<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>